#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# ${1} usually resolves to ".git/COMMIT_EDITMSG"
if [ -z "${1}" ]; then
	echo " Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(head <"${1}" -n1)"

# ignore merge requests
if echo "${commitTitle}" | grep -qE "^Merge branch \'"; then
	echo " Commit hook: ignoring branch merge"
	exit 0
fi

# check semantic versioning scheme
if ! echo "${commitTitle}" | grep -qE '^(?:feat|fix|build|chore|ci|docs|style|refactor|perf|test)(?:\((?:\w|\s|\-|_)+\))?(?:!)?:\s\w+'; then
	# the first line is automatically prefixed by one space
	echo " Commit hook: Your commit title did not follow the conventional commits specification: ${commitTitle}"
	echo "  Commit hook: Allowed prefixes are: feat, fix, build, chore, ci, docs, style, refactor, perf, test"
	echo "  Commit hook: Please see https://www.conventionalcommits.org/en/v1.0.0/"
	exit 1
fi
